// src/entities/planet.ts (Store Density)

import { AU_IN_METERS } from '../constants/physics';
import { PLANET_TYPES } from '../constants/planetary';
import { ELEMENTS, MineralRichness } from '../constants/resources';
import { PRNG } from '../utils/prng';
import { RgbColour } from '../rendering/colour';
import { logger } from '../utils/logger';
// Import the specific interface from the generator file
import { generatePlanetCharacteristics, PlanetCharacteristics, PlanetGenerationOptions } from './planet/planet_characteristics_generator';
import { StellarEnvironment, getDefaultStellarEnvironment } from './stellar_environment';
import { OrbitHost } from './stellar_body';
// Import the generator and data interface
import { SurfaceData, SurfaceGenerationRequest } from './planet/surface_generator';
import { getSurfaceGenerationProvider } from './planet/surface_generation_provider';
import { isLiquidCovered, SurfaceLiquidOverlay } from './planet/surface_liquid';
// Re-export needed types if they aren't in a shared file
export type AtmosphereComposition = Record<string, number>;
//
export interface Atmosphere {
  //
  density: string; //
  pressure: number; //
  composition: AtmosphereComposition; //
}

export function describePlanetType(type: string): string {
  switch (type) {
    case 'GasGiant':
      return 'gas giant';
    case 'IceGiant':
      return 'ice giant';
    case 'Oceanic':
      return 'ocean world';
    case 'Hycean':
      return 'hycean world';
    case 'Greenhouse':
      return 'greenhouse world';
    case 'CarbonRich':
      return 'carbon-rich world';
    case 'Chthonian':
      return 'chthonian world';
    case 'Cryovolcanic':
      return 'cryovolcanic world';
    case 'DwarfIce':
      return 'dwarf ice world';
    case 'Molten':
      return 'molten terrestrial world';
    case 'Rock':
      return 'rocky terrestrial world';
    case 'Frozen':
      return 'frozen world';
    case 'Lunar':
      return 'lunar body';
    default:
      return type.replace(/([a-z])([A-Z])/g, '$1 $2').toLowerCase();
  }
}

/** Represents a planet, holding data generated by other modules. */
export class Planet {
  //
  // Core Identification & Orbit
  public readonly name: string;
  public readonly type: string; //
  public readonly orbitDistance: number; //
  public orbitAngle: number; // Mutable
  public systemX: number; // Mutable
  public systemY: number; // Mutable
  public readonly orbitHost: OrbitHost;

  // Physical Characteristics (Generated)
  public readonly diameter: number; //
  public readonly density: number; // *** NEW: Store density ***
  public readonly gravity: number; // Now calculated by generator
  public readonly surfaceTemp: number; //
  public readonly surfaceTempMin: number;
  public readonly surfaceTempMax: number;
  public readonly atmosphere: Atmosphere; //
  public readonly hydrosphere: string; //
  public readonly lithosphere: string; //
  public readonly magneticFieldStrength: number;
  public readonly mass: number; // Mass (kg)
  public readonly escapeVelocity: number;
  public readonly axialTilt: number; // in radians
  public readonly tidallyLocked: boolean;
  public readonly rotationPeriodHours: number;
  public readonly orbitalInclination: number; // in radians

  // Resources & Gameplay (Generated + State)
  public readonly mineralRichness: MineralRichness; // Kept for summary/potential use
  public readonly baseMinerals: number; // Kept for summary/potential use
  public readonly elementAbundance: Record<string, number>; // Overall planet abundance
  public scanned: boolean = false; //
  public primaryResource: string | null = null; // Determined by scan()
  public minedLocations: Set<string> = new Set(); // Track depleted locations (key: "x,y")
  public minedLocationAmounts: Record<string, number> = {}; // Track partially extracted deposit units.

  // Generation & State
  public readonly systemPRNG: PRNG; //
  public readonly mapSeed: string; //
  private readonly stellarEnvironment: StellarEnvironment;

  // Surface Data (Lazy Loaded/Cached)
  private _surfaceData: SurfaceData | null = null; // Holds heightmap, colors, AND element map
  private _surfaceGenerationPromise: Promise<void> | null = null;

  // Moons (Placeholder)
  public moons: Planet[] = []; //

  constructor(
    //
    name: string,
    type: string,
    orbitDistance: number,
    angle: number,
    systemPRNG: PRNG, // PRNG seeded for the parent system
    parentStarType: string,
    characteristics?: PlanetCharacteristics,
    stellarEnvironment?: StellarEnvironment,
    orbitHost?: OrbitHost,
    orbitCenterX: number = 0,
    orbitCenterY: number = 0,
    totalFlux_W_m2?: number,
    generationOptions?: PlanetGenerationOptions
  ) {
    this.name = name; //
    this.type = type; //
    this.orbitDistance = orbitDistance; //
    this.orbitAngle = angle; //
    this.orbitHost = orbitHost ?? { kind: 'barycentric' };
    this.stellarEnvironment = stellarEnvironment ?? getDefaultStellarEnvironment(parentStarType);

    // Seed PRNG specifically for this planet
    this.systemPRNG = systemPRNG.seedNew('planet_' + name); //
    logger.debug(`[Planet:${this.name}] Initialized PRNG with seed: ${this.systemPRNG.getInitialSeed()}`); //

    // Use provided characteristics or generate new ones
    const finalCharacteristics = characteristics ?? generatePlanetCharacteristics(
        this.type,
        this.orbitDistance,
        this.systemPRNG,
        parentStarType,
        this.stellarEnvironment,
        totalFlux_W_m2,
        generationOptions
    );

    // Assign properties from finalCharacteristics
    this.diameter = finalCharacteristics.diameter;
    this.density = finalCharacteristics.density;
    this.gravity = finalCharacteristics.gravity;
    this.mass = finalCharacteristics.mass;
    this.escapeVelocity = finalCharacteristics.escapeVelocity;
    this.atmosphere = finalCharacteristics.atmosphere;
    this.surfaceTemp = finalCharacteristics.surfaceTemp;
    this.surfaceTempMin = finalCharacteristics.surfaceTempMin;
    this.surfaceTempMax = finalCharacteristics.surfaceTempMax;
    this.hydrosphere = finalCharacteristics.hydrosphere;
    this.lithosphere = finalCharacteristics.lithosphere;
    this.magneticFieldStrength = finalCharacteristics.magneticFieldStrength;
    this.axialTilt = finalCharacteristics.axialTilt;
    this.tidallyLocked = finalCharacteristics.tidallyLocked;
    this.rotationPeriodHours = finalCharacteristics.rotationPeriodHours;
    this.orbitalInclination = finalCharacteristics.orbitalInclination;
    this.mineralRichness = finalCharacteristics.mineralRichness;
    this.baseMinerals = finalCharacteristics.baseMinerals;
    this.elementAbundance = finalCharacteristics.elementAbundance;

    // Initial position
    this.systemX = orbitCenterX + Math.cos(this.orbitAngle) * this.orbitDistance;
    this.systemY = orbitCenterY + Math.sin(this.orbitAngle) * this.orbitDistance;

    // Map seed for surface generation
    this.mapSeed = this.systemPRNG.getInitialSeed() + '_map'; //

    // Log summary
    const topElements = Object.entries(this.elementAbundance)
      .filter(([, abundance]) => abundance > 0)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 3) // Get top 3
      .map(([key]) => ELEMENTS[key]?.name || key) // Use proper name if available
      .join(', ');

    logger.info(
      `[Planet:${this.name}] Constructed. Type=${this.type}, Orbit=${this.orbitDistance.toFixed(0)}, Temp=${
        this.surfaceTemp
      }K (${this.surfaceTempMin}-${this.surfaceTempMax}K), Gravity=${this.gravity.toFixed(2)}g, Density=${this.density.toFixed(2)}g/cm³, Minerals=${
        this.mineralRichness
      }. Top Elements: [${topElements || 'None'}]`
    ); // Updated log
    //

    // Do NOT generate surface data in constructor for lazy loading
  }

  // --- Getters for Lazy-Loaded Surface Data ---
  get heightmap(): number[][] | null {
    //
    if (!this._surfaceData && this.type !== 'GasGiant' && this.type !== 'IceGiant') {
      //
      this.ensureSurfaceReady(); // Generate if needed
    }
    return this._surfaceData?.heightmap ?? null; //
  }

  get heightLevelColors(): string[] | null {
    //
    if (!this._surfaceData && this.type !== 'GasGiant' && this.type !== 'IceGiant') {
      //
      this.ensureSurfaceReady(); // Generate if needed
    }
    return this._surfaceData?.heightLevelColors ?? null; //
  }

  get rgbPaletteCache(): RgbColour[] | null {
    //
    if (!this._surfaceData) {
      // Generate even for solid planets as height colors depend on it
      this.ensureSurfaceReady(); // Generate if needed
    }
    return this._surfaceData?.rgbPaletteCache ?? null; //
  }

  // Getter for Surface Element Map
  get surfaceElementMap(): string[][] | null {
    //
    if (!this._surfaceData && this.type !== 'GasGiant' && this.type !== 'IceGiant') {
      //
      this.ensureSurfaceReady(); // Generate if needed
    }
    return this._surfaceData?.surfaceElementMap ?? null; // Access from _surfaceData
  }

  get surfaceLiquid(): SurfaceLiquidOverlay | null {
    if (!this._surfaceData && this.type !== 'GasGiant' && this.type !== 'IceGiant') {
      this.ensureSurfaceReady();
    }
    return this._surfaceData?.liquidOverlay ?? null;
  }

  getSurfaceDataIfReady(): SurfaceData | null {
    return this._surfaceData;
  }

  isSubmergedSurface(x: number, y: number): boolean {
    const map = this.heightmap;
    const liquid = this.surfaceLiquid;
    if (!map || !liquid || map.length === 0) return false;
    const wrappedX = ((x % map.length) + map.length) % map.length;
    const wrappedY = ((y % map.length) + map.length) % map.length;
    return isLiquidCovered(map[wrappedY]?.[wrappedX] ?? 0, liquid);
  }

  /** Ensures surface data (including element map) is generated and cached if needed. Throws on failure. */
  ensureSurfaceReady(): void {
    //
    if (this._surfaceData) {
      //
      logger.debug(`[Planet:${this.name}] Surface data already generated.`); //
      return; // Already generated
    }

    logger.info(`[Planet:${this.name}] ensureSurfaceReady: Generating surface data...`); //
    try {
      //
      this._surfaceData = getSurfaceGenerationProvider().generateSurfaceData(this.createSurfaceGenerationRequest()); //
      this.validateSurfaceData();
      logger.info(`[Planet:${this.name}] Surface data generated successfully.`); //
    } catch (error) {
      //
      logger.error(`[Planet:${this.name}] Surface data generation failed: ${error}`); //
      this._surfaceData = null; // Ensure it's null on failure
      throw error; // Re-throw after logging
    }
  }

  async prepareSurfaceReady(): Promise<void> {
    if (this._surfaceData) return;
    if (this._surfaceGenerationPromise) return this._surfaceGenerationPromise;

    const provider = getSurfaceGenerationProvider();
    if (!provider.generateSurfaceDataAsync) {
      this.ensureSurfaceReady();
      return;
    }

    this._surfaceGenerationPromise = provider.generateSurfaceDataAsync(this.createSurfaceGenerationRequest())
      .then((data) => {
        this._surfaceData = data;
        this.validateSurfaceData();
        logger.info(`[Planet:${this.name}] Surface data generated asynchronously.`);
      })
      .catch((error) => {
        this._surfaceData = null;
        logger.error(`[Planet:${this.name}] Async surface data generation failed: ${error}`);
        throw error;
      })
      .finally(() => {
        this._surfaceGenerationPromise = null;
      });
    return this._surfaceGenerationPromise;
  }

  prepareSurfaceInBackground(): void {
    const provider = getSurfaceGenerationProvider();
    if (!provider.generateSurfaceDataAsync || this._surfaceData || this._surfaceGenerationPromise) return;
    void this.prepareSurfaceReady().catch((error) => {
      logger.warn(`[Planet:${this.name}] Background surface preparation failed: ${error}`);
    });
  }

  private createSurfaceGenerationRequest(): SurfaceGenerationRequest {
    return {
      planetType: this.type,
      mapSeed: this.mapSeed,
      prngSeed: this.systemPRNG.getInitialSeed(),
      atmosphere: this.atmosphere,
      planetAbundance: this.elementAbundance,
      profile: {
        mineralRichness: this.mineralRichness,
        baseMinerals: this.baseMinerals,
        metallicityFeH: this.stellarEnvironment.metallicityFeH,
        surfaceTemp: this.surfaceTemp,
        hydrosphere: this.hydrosphere,
      },
    };
  }

  private validateSurfaceData(): void {
    if (!this._surfaceData) {
      throw new Error('Surface generator returned null data.');
    }
    const isSolid = this.type !== 'GasGiant' && this.type !== 'IceGiant';
    if (
      isSolid &&
      (!this._surfaceData.heightmap ||
        this._surfaceData.heightmap.length === 0 ||
        !this._surfaceData.heightLevelColors ||
        this._surfaceData.heightLevelColors.length === 0 ||
        !this._surfaceData.surfaceElementMap ||
        this._surfaceData.surfaceElementMap.length === 0)
    ) {
      const missing = [];
      if (!this._surfaceData.heightmap || this._surfaceData.heightmap.length === 0) missing.push('heightmap');
      if (!this._surfaceData.heightLevelColors || this._surfaceData.heightLevelColors.length === 0)
        missing.push('heightLevelColors');
      if (!this._surfaceData.surfaceElementMap || this._surfaceData.surfaceElementMap.length === 0)
        missing.push('surfaceElementMap');
      throw new Error(`Surface generator returned incomplete data for solid planet (missing/empty: ${missing.join(', ')}).`);
    }
    if (!isSolid && (!this._surfaceData.rgbPaletteCache || this._surfaceData.rgbPaletteCache.length === 0)) {
      throw new Error('Surface generator returned incomplete data for gas/ice giant (missing/empty palette).');
    }
  }

  /** Performs a scan, determining the primary resource based on abundance. */
  scan(): void {
    //
    if (this.scanned) {
      //
      logger.info(`[Planet:${this.name}] Scan attempted, but already scanned.`); //
      return; //
    }
    logger.info(`[Planet:${this.name}] Scanning planet...`); //
    this.scanned = true; //

    let highestAbundance = -1; //
    let potentialResource = 'None Detected'; //

    // Prioritize more valuable non-common elements
    const valuableElements = Object.entries(this.elementAbundance)
      .filter(
        ([key, abundance]) =>
          abundance > 0 &&
          ![
            'SILICON',
            'WATER_ICE',
            'CARBON',
            'IRON',
            'ALUMINIUM',
            'MAGNESIUM',
            'SULFUR',
            'PHOSPHORUS',
            'POTASSIUM',
          ].includes(key)
      )
      .sort(([, a], [, b]) => b - a); // Sort descending by abundance

    if (valuableElements.length > 0) {
      const [key, abundance] = valuableElements[0];
      this.primaryResource = ELEMENTS[key]?.name || key;
      highestAbundance = abundance;
      potentialResource = this.primaryResource;
    } else {
      // If no valuable elements, find the most abundant common one
      const anyElements = Object.entries(this.elementAbundance)
        .filter(([, abundance]) => abundance > 0)
        .sort(([, a], [, b]) => b - a);
      if (anyElements.length > 0) {
        const [key, abundance] = anyElements[0];
        this.primaryResource = ELEMENTS[key]?.name || key;
        highestAbundance = abundance;
        potentialResource = this.primaryResource;
      } else {
        this.primaryResource = 'None Detected';
      }
    }

    // Bonus check for exceptional richness yielding a rare resource override
    if (this.mineralRichness === MineralRichness.ULTRA_RICH && this.systemPRNG.random() < 0.2) {
      const rareResources = [
        'GOLD',
        'PLATINUM',
        'PALLADIUM',
        'RHODIUM',
        'URANIUM',
        'NEODYMIUM',
        'DYSPROSIUM',
        'INDIUM',
      ];
      // Choose from rare resources that *actually exist* on the planet
      const possibleRares = rareResources.filter((r) => this.elementAbundance[r] > 0);
      if (possibleRares.length > 0) {
        const chosenRareKey = this.systemPRNG.choice(possibleRares)!;
        const oldResource = this.primaryResource;
        this.primaryResource = ELEMENTS[chosenRareKey]?.name || chosenRareKey;
        logger.info(
          `[Planet:${this.name}] Exceptional richness yielded rare resource: ${this.primaryResource} (overwriting ${oldResource})`
        );
        potentialResource = this.primaryResource; // Update the potential resource as well
      }
    }

    logger.info(
      `[Planet:${
        this.name
      }] Scan complete. Primary Resource: ${potentialResource} (Abundance Value: ${highestAbundance.toFixed(
        0
      )}), Richness Category: ${this.mineralRichness}`
    ); //
  }

  /** Returns multi-line scan information for the planet, including moon summary. */
  getScanInfo(): string[] {
    logger.debug(`[Planet:${this.name}] getScanInfo called (Scanned: ${this.scanned})`);
    const orbitText = this.orbitDistance <= 0 ? 'none' : `${(this.orbitDistance / AU_IN_METERS).toFixed(3)} AU`;
    const infoLines: string[] = [
      `<h>--- SCAN REPORT: ${this.name} ---</h>`,
      `Type: <hl>${describePlanetType(this.type)}</hl>`,
      `Orbit: <hl>${orbitText}</hl>`,
    ];

    // --- Common Physical Properties ---
    // Use toLocaleString for diameter, toFixed for others
    infoLines.push(
      `Diameter: <hl>${this.diameter.toLocaleString()} km</hl> | Density: <hl>${this.density.toFixed(
        2
      )} g/cm³</hl> | Gravity: <hl>${this.gravity.toFixed(2)} G</hl>`
    );
    // Add Mass and Escape Velocity if desired
    // infoLines.push(`Mass: <hl>${this.mass.toExponential(2)} kg</hl> | Escape Vel: <hl>${this.escapeVelocity.toFixed(0)} m/s</hl>`);
    infoLines.push(
      `Surface Temp: <hl>avg ${this.surfaceTemp} K</hl> | <hl>min ${this.surfaceTempMin} K</hl> | <hl>max ${this.surfaceTempMax} K</hl>`
    );
    infoLines.push(
      `Rotation: <hl>${this.tidallyLocked ? 'Tidally locked' : 'Free'}</hl> | Axial Tilt: <hl>${(
        (this.axialTilt * 180) /
        Math.PI
      ).toFixed(1)} deg</hl> | Period: <hl>${this.getRotationPeriodLabel()}</hl> | Inclination: <hl>${((this.orbitalInclination * 180) / Math.PI).toFixed(1)} deg</hl>`
    );

    // --- Atmosphere Details ---
    let pressureText = this.atmosphere.pressure < 0.001 ? '~0' : this.atmosphere.pressure.toFixed(3);
    infoLines.push(`Atmosphere: <hl>${this.atmosphere.density} (${pressureText} bar</hl>)`);
    let compStr = '<hl>None</hl>';
    const comp = this.atmosphere.composition;
    if (comp && Object.keys(comp).length > 0 && comp['None'] !== 100) {
      const sortedComp = Object.entries(comp)
        .filter(([, percent]) => percent > 0.1) // Show components > 0.1%
        .sort(([, a], [, b]) => b - a);
      compStr = sortedComp.map(([gas, percent]) => `<hl>${gas}: ${percent.toFixed(1)}%</hl>`).join(', ');
      if (sortedComp.length === 0) compStr = '<hl>Trace Gases</hl>'; // Handle case where all are < 0.1%
    }
    infoLines.push(`Composition: ${compStr}`);

    // --- Surface Descriptors ---
    infoLines.push(`Hydrosphere: <hl>${this.hydrosphere}</hl>`);
    infoLines.push(`Lithosphere: <hl>${this.lithosphere}</hl>`);

    // --- Moon Information --- <<< NEW SECTION >>>
    if (this.moons && this.moons.length > 0) {
      const moonCounts: Record<string, number> = {};
      this.moons.forEach((moon) => {
        moonCounts[moon.type] = (moonCounts[moon.type] || 0) + 1;
      });
      const moonSummary = Object.entries(moonCounts)
        .map(([type, count]) => `${count} ${describePlanetType(type)}`)
        .join(', ');
      infoLines.push(`Moons Detected: <hl>${this.moons.length}</hl> (${moonSummary})`);
    } else {
      // Only show "None" for types that *could* have moons
      if (['Rock', 'Oceanic', 'Frozen', 'GasGiant', 'IceGiant'].includes(this.type)) {
        infoLines.push(`Moons Detected: <hl>None</hl>`);
      }
    }
    // --- End Moon Information ---

    // --- Resource Information ---
    // Differentiate scan results for Gas/Ice Giants vs. Solid bodies
    if (this.type === 'GasGiant' || this.type === 'IceGiant') {
      const topElements = Object.entries(this.elementAbundance)
        .filter(([, abundance]) => abundance > 0.1) // Show elements > 0.1% abundance
        .sort(([, a], [, b]) => b - a)
        .slice(0, 3) // Show top 3
        .map(([key]) => `<hl>${ELEMENTS[key]?.name || key}</hl>`)
        .join(', ');
      infoLines.push(`Atmospheric Resources: <hl>${topElements || 'Trace Amounts'}</hl>`);
      infoLines.push(`Refueling: Possible via <hl>atmospheric scoop</hl>.`);
      infoLines.push(`Mining: [-W-]N/A (Gas Giant)</w>`);
    } else {
      // Solid planet resource info
      if (this.scanned) {
        const topElements = Object.entries(this.elementAbundance)
          .filter(([, abundance]) => abundance > 0.1) // Show elements > 0.1%
          .sort(([, a], [, b]) => b - a)
          .slice(0, 5) // Show top 5 perhaps
          .map(([key, abundance]) => `${ELEMENTS[key]?.name || key} (${abundance.toFixed(1)}%)`) // Show name and abundance %
          .join(', ');
        infoLines.push(
          `Mineral Scan: <hl>${this.mineralRichness}</hl>. Primary: <hl>${this.primaryResource || 'N/A'}</hl>.`
        );
        infoLines.push(`Est. Deposits: <hl>${topElements || 'None Significant'}</hl>`); // Display the top elements string
      } else {
        infoLines.push(`Mineral Scan: Requires planetary scan. Richness potential: <hl>${this.mineralRichness}</hl>.`);
      }
    }

    infoLines.push('<h>--- SCAN COMPLETE ---</h>');
    return infoLines;
  }

  /** Checks if a specific surface coordinate has been mined. */
  isMined(x: number, y: number): boolean {
    return this.minedLocations.has(`${x},${y}`);
  }

  /** Returns how many units have been extracted from a specific surface coordinate. */
  getMinedAmount(x: number, y: number): number {
    return Math.max(0, this.minedLocationAmounts[`${x},${y}`] || 0);
  }

  /** Adds extracted units to a coordinate and marks the location depleted when its yield is exhausted. */
  recordMinedAmount(x: number, y: number, amount: number, totalYield: number): void {
    const key = `${x},${y}`;
    this.minedLocationAmounts[key] = Math.round((this.getMinedAmount(x, y) + Math.max(0, amount)) * 10) / 10;
    if (this.minedLocationAmounts[key] >= Math.max(0.1, totalYield) - 0.0001) {
      this.markMined(x, y);
    }
  }

  /** Marks a specific surface coordinate as mined. */
  markMined(x: number, y: number): void {
    const key = `${x},${y}`;
    if (!this.minedLocations.has(key)) {
      this.minedLocations.add(key);
      logger.debug(`[Planet:${this.name}] Marked location [${x},${y}] as mined.`);
    }
  }

  /**
   * Calculates the approximate current surface temperature within the generated min/max range.
   * Assumes orbitAngle 0 is an equinox and uses axial tilt for seasonal bias.
   * @param latitude Optional latitude (in radians, -PI/2 to PI/2).
   * @returns The estimated current temperature in Kelvin.
   */
  public getCurrentTemperature(latitude: number = 0): number {
    const min = Math.min(this.surfaceTempMin, this.surfaceTempMax, this.surfaceTemp);
    const max = Math.max(this.surfaceTempMin, this.surfaceTempMax, this.surfaceTemp);
    if (max <= min) return Math.max(2, Math.round(this.surfaceTemp));

    const seasonalSine = Math.sin(this.orbitAngle) * Math.sin(this.axialTilt);
    const seasonalOffset = seasonalSine * (max - min) * 0.35;
    const latitudeFactor = Math.max(0, Math.min(1, Math.cos(latitude)));
    const latitudeBias = 0.72 + latitudeFactor * 0.28;
    const adjusted = min + (this.surfaceTemp + seasonalOffset - min) * latitudeBias;

    return Math.max(2, Math.round(Math.max(min, Math.min(max, adjusted))));
  }

  public getRotationPeriodLabel(): string {
    if (this.tidallyLocked) return 'synchronous';
    const hours = this.rotationPeriodHours;
    if (!Number.isFinite(hours) || hours <= 0) return 'unknown';
    if (hours >= 48) return `${(hours / 24).toFixed(1)} days`;
    return `${hours.toFixed(1)} hours`;
  }
} // End Planet class //
